package engine

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// PlannerAction represents a single concrete step generated by a PDDL solver
type PlannerAction struct {
	Name       string
	Parameters []string
}

// PlanningEngine defines the interface for our dual-tier cognitive planners
type PlanningEngine interface {
	// Solve takes raw PDDL domain and problem strings, and returns a sequential
	// slice of actions required to achieve the goal, or an error if no valid plan exists.
	Solve(ctx context.Context, domain string, problem string) ([]PlannerAction, error)
}

// -----------------------------------------------------------------------------
// TIER 1: Native Go STRIPS Solver (System 1)
// -----------------------------------------------------------------------------

type NativePlanner struct{}

func NewNativePlanner() *NativePlanner {
	return &NativePlanner{}
}

func (p *NativePlanner) Solve(ctx context.Context, domain string, problem string) ([]PlannerAction, error) {
	// TODO: Implement a lightweight BFS/A* forward-chaining STRIPS solver.
	// This will parse basic PDDL in memory and solve it natively without external binaries.
	// For now, this is a placeholder that falls back.
	return nil, fmt.Errorf("native PDDL parsing and BFS solver not yet implemented; delegate to Tier 2")
}

// -----------------------------------------------------------------------------
// TIER 2: Fast Downward PDDL Solver (System 2)
// -----------------------------------------------------------------------------

type FastDownwardPlanner struct {
	BinaryPath string
}

// NewFastDownwardPlanner creates a wrapper for an arm's-length external Fast Downward binary.
func NewFastDownwardPlanner(binaryPath string) *FastDownwardPlanner {
	if binaryPath == "" {
		binaryPath = "downward" // Assumes it is available in PATH
	}
	return &FastDownwardPlanner{BinaryPath: binaryPath}
}

func (p *FastDownwardPlanner) Solve(ctx context.Context, domain string, problem string) ([]PlannerAction, error) {
	// 1. Create a secure, isolated temporary directory for the PDDL files
	tempDir, err := os.MkdirTemp("", "pddl_*")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir for fast-downward: %w", err)
	}
	defer os.RemoveAll(tempDir) // Ensure cleanup

	domainPath := filepath.Join(tempDir, "domain.pddl")
	if err := os.WriteFile(domainPath, []byte(domain), 0644); err != nil {
		return nil, fmt.Errorf("failed to write domain.pddl: %w", err)
	}

	problemPath := filepath.Join(tempDir, "problem.pddl")
	if err := os.WriteFile(problemPath, []byte(problem), 0644); err != nil {
		return nil, fmt.Errorf("failed to write problem.pddl: %w", err)
	}

	// 2. Execute Fast Downward as an arm's length subprocess
	// We use the "lama-first" alias which is extremely fast for finding an initial valid plan
	cmd := exec.CommandContext(ctx, p.BinaryPath, "--alias", "lama-first", domainPath, problemPath)
	cmd.Dir = tempDir
	
	// We capture combined output for debugging, but we primarily care about the generated sas_plan file
	output, _ := cmd.CombinedOutput()

	// 3. Verify if a plan was actually generated (Fast Downward creates 'sas_plan' on success)
	planPath := filepath.Join(tempDir, "sas_plan")
	if _, statErr := os.Stat(planPath); os.IsNotExist(statErr) {
		return nil, fmt.Errorf("fast downward failed to find a valid timeline/plan. Contradiction likely. Output:\n%s", string(output))
	}

	// 4. Parse the standard PDDL action output
	planData, err := os.ReadFile(planPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read sas_plan output: %w", err)
	}

	return parseFastDownwardPlan(string(planData))
}

// parseFastDownwardPlan cleanly extracts the step sequence from the raw sas_plan text
func parseFastDownwardPlan(planText string) ([]PlannerAction, error) {
	var actions []PlannerAction
	lines := strings.Split(planText, "\n")
	
	for _, line := range lines {
		line = strings.TrimSpace(line)
		
		// Skip empty lines and comment lines (Fast Downward appends plan costs like "; cost = 5")
		if line == "" || strings.HasPrefix(line, ";") {
			continue
		}
		
		// Actions are output in format: (action_name param1 param2)
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, ")")
		parts := strings.Fields(line)
		
		if len(parts) > 0 {
			actions = append(actions, PlannerAction{
				Name:       parts[0],
				Parameters: parts[1:],
			})
		}
	}
	
	return actions, nil
}
