package engine

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strings"
)

// PlannerAction represents a single concrete step generated by a PDDL solver
type PlannerAction struct {
	Name       string
	Parameters []string
}

// PlanningEngine defines the interface for our dual-tier cognitive planners
type PlanningEngine interface {
	// Solve takes raw PDDL domain and problem strings, and returns a sequential
	// slice of actions required to achieve the goal, or an error if no valid plan exists.
	Solve(ctx context.Context, domain string, problem string) ([]PlannerAction, error)
}

// -----------------------------------------------------------------------------
// TIER 1: Native Go STRIPS Solver (System 1)
// -----------------------------------------------------------------------------

type NativePlanner struct{}

func NewNativePlanner() *NativePlanner {
	return &NativePlanner{}
}

// StripsAction represents a grounded propositional action for the BFS planner
type StripsAction struct {
	Name          string
	Preconditions []string
	AddEffects    []string
	DelEffects    []string
}

func (p *NativePlanner) Solve(ctx context.Context, domain string, problem string) ([]PlannerAction, error) {
	// 1. Basic Regex/String parsing for the initial state and goal
	// In a production solver this would use a full S-expression parser, but for 
	// GLLAM 0.2 we just need a robust propositional state extractor.
	initialState := extractPredicates(problem, "(:init", ")")
	goalState := extractPredicates(problem, "(:goal", ")")

	if len(goalState) == 0 {
		return []PlannerAction{}, nil // Goal already met or empty
	}

	// 2. Parse Actions from domain (Stubbed for now until Procedural actions are injected)
	// We will extract (:action ...) blocks using a similar naive parser.
	var actions []StripsAction
	// TODO: Parse 'domain' string for actual actions. 
	
	// 3. Execute Breadth-First-Search (BFS)
	plan := p.bfs(initialState, goalState, actions)
	if plan == nil {
		return nil, fmt.Errorf("native BFS solver exhausted all states; no valid timeline/plan exists")
	}

	return plan, nil
}

// extractPredicates is a naive parser to extract "(predicate a b)" strings
func extractPredicates(pddl string, blockStart string, blockEnd string) map[string]bool {
	state := make(map[string]bool)
	startIdx := strings.Index(pddl, blockStart)
	if startIdx == -1 {
		return state
	}
	// Extract the block contents roughly
	block := pddl[startIdx+len(blockStart):]
	endIdx := strings.Index(block, blockEnd)
	if endIdx != -1 {
		block = block[:endIdx]
	}
	
	// Find all "(...)" segments
	parts := strings.Split(block, "(")
	for _, p := range parts {
		idx := strings.Index(p, ")")
		if idx != -1 {
			pred := strings.TrimSpace(p[:idx])
			if pred != "" && !strings.HasPrefix(pred, "and") {
				state[pred] = true
			}
		}
	}
	return state
}

func (p *NativePlanner) bfs(initial map[string]bool, goals map[string]bool, actions []StripsAction) []PlannerAction {
	type Node struct {
		State map[string]bool
		Plan  []PlannerAction
	}
	
	queue := []Node{{State: initial, Plan: []PlannerAction{}}}
	visited := make(map[string]bool)
	visited[stateToStr(initial)] = true

	for len(queue) > 0 {
		curr := queue[0]
		queue = queue[1:]

		// Check if goal is satisfied
		goalMet := true
		for g := range goals {
			if !curr.State[g] {
				goalMet = false
				break
			}
		}
		if goalMet {
			return curr.Plan
		}

		// Apply all valid actions
		for _, a := range actions {
			possible := true
			for _, pre := range a.Preconditions {
				if !curr.State[pre] {
					possible = false
					break
				}
			}
			if !possible {
				continue
			}

			// Compute next state
			nextState := make(map[string]bool)
			for k, v := range curr.State {
				nextState[k] = v
			}
			for _, del := range a.DelEffects {
				delete(nextState, del)
			}
			for _, add := range a.AddEffects {
				nextState[add] = true
			}

			nextStr := stateToStr(nextState)
			if !visited[nextStr] {
				visited[nextStr] = true
				
				newPlan := make([]PlannerAction, len(curr.Plan))
				copy(newPlan, curr.Plan)
				newPlan = append(newPlan, PlannerAction{Name: a.Name})
				
				queue = append(queue, Node{State: nextState, Plan: newPlan})
			}
		}
	}
	return nil // Plan not found
}

func stateToStr(state map[string]bool) string {
	var keys []string
	for k := range state {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return strings.Join(keys, "|")
}

// -----------------------------------------------------------------------------
// TIER 2: Fast Downward PDDL Solver (System 2)
// -----------------------------------------------------------------------------

type FastDownwardPlanner struct {
	BinaryPath string
}

// NewFastDownwardPlanner creates a wrapper for an arm's-length external Fast Downward binary.
func NewFastDownwardPlanner(binaryPath string) *FastDownwardPlanner {
	if binaryPath == "" {
		binaryPath = "downward" // Assumes it is available in PATH
	}
	return &FastDownwardPlanner{BinaryPath: binaryPath}
}

func (p *FastDownwardPlanner) Solve(ctx context.Context, domain string, problem string) ([]PlannerAction, error) {
	// 1. Create a secure, isolated temporary directory for the PDDL files
	tempDir, err := os.MkdirTemp("", "pddl_*")
	if err != nil {
		return nil, fmt.Errorf("failed to create temp dir for fast-downward: %w", err)
	}
	defer os.RemoveAll(tempDir) // Ensure cleanup

	domainPath := filepath.Join(tempDir, "domain.pddl")
	if err := os.WriteFile(domainPath, []byte(domain), 0644); err != nil {
		return nil, fmt.Errorf("failed to write domain.pddl: %w", err)
	}

	problemPath := filepath.Join(tempDir, "problem.pddl")
	if err := os.WriteFile(problemPath, []byte(problem), 0644); err != nil {
		return nil, fmt.Errorf("failed to write problem.pddl: %w", err)
	}

	// 2. Execute Fast Downward as an arm's length subprocess
	// We use the "lama-first" alias which is extremely fast for finding an initial valid plan
	cmd := exec.CommandContext(ctx, p.BinaryPath, "--alias", "lama-first", domainPath, problemPath)
	cmd.Dir = tempDir
	
	// We capture combined output for debugging, but we primarily care about the generated sas_plan file
	output, _ := cmd.CombinedOutput()

	// 3. Verify if a plan was actually generated (Fast Downward creates 'sas_plan' on success)
	planPath := filepath.Join(tempDir, "sas_plan")
	if _, statErr := os.Stat(planPath); os.IsNotExist(statErr) {
		return nil, fmt.Errorf("fast downward failed to find a valid timeline/plan. Contradiction likely. Output:\n%s", string(output))
	}

	// 4. Parse the standard PDDL action output
	planData, err := os.ReadFile(planPath)
	if err != nil {
		return nil, fmt.Errorf("failed to read sas_plan output: %w", err)
	}

	return parseFastDownwardPlan(string(planData))
}

// parseFastDownwardPlan cleanly extracts the step sequence from the raw sas_plan text
func parseFastDownwardPlan(planText string) ([]PlannerAction, error) {
	var actions []PlannerAction
	lines := strings.Split(planText, "\n")
	
	for _, line := range lines {
		line = strings.TrimSpace(line)
		
		// Skip empty lines and comment lines (Fast Downward appends plan costs like "; cost = 5")
		if line == "" || strings.HasPrefix(line, ";") {
			continue
		}
		
		// Actions are output in format: (action_name param1 param2)
		line = strings.TrimPrefix(line, "(")
		line = strings.TrimSuffix(line, ")")
		parts := strings.Fields(line)
		
		if len(parts) > 0 {
			actions = append(actions, PlannerAction{
				Name:       parts[0],
				Parameters: parts[1:],
			})
		}
	}
	
	return actions, nil
}
