(define (problem gllam_problem)
  (:domain gllam)

  (:objects
    project_deadline event_revise_apr_5 cover_letter_revision july_25_workshop cover_letter_submission write_skills one_on_one_with_greg event_final_review write_introduction documentary_production_2022 creative_director_zoom_call event_write_second_accomplishment initial_revisions event_incorporate_revisions final_edits write_accomplishments write_conclusion workshop_preparation seek_feedback cover_letter_draft_completion event_submission greg_coaching_session event_write_skills_accomplishment storytelling_workshop creative_director_meeting leslie_workshop_april_18 event_outline_cover_letter finalize_draft cover_letter_feedback mock_interview_greg cover_letter_revision_april_5 feedback_deadline_apr14 zoom_call_creative_director progress_report_july_15 event_polish_cover_letter cover_letter_feedback_request meeting_with_laura team_meeting event_submit_cover_letter event_incorporate_feedback cover_letter_final_review cover_letter_draft_march_25 event_draft_mar_25 caribbean_heritage_lunch cover_letter_submission_greg greg_feedback_deadline leslie_networking_event july_18_presentation july_22_project_deadline event_workshop_mar_20 - event
    cover_letter_deadline - constraint
  )

  (:init
    (happened_before creative_director_zoom_call one_on_one_with_greg)
    (happened_before leslie_workshop_april_18 zoom_call_creative_director)
    (happened_before event_outline_cover_letter finalize_draft)
    (happened_before cover_letter_submission_greg greg_feedback_deadline)
    (happened_before event_final_review event_submission)
    (happened_before event_write_second_accomplishment finalize_draft)
    (happened_before leslie_networking_event event_revise_apr_5)
    (happened_before finalize_draft initial_revisions)
    (happened_before greg_coaching_session cover_letter_revision)
    (happened_after july_18_presentation progress_report_july_15)
    (happened_before july_22_project_deadline july_25_workshop)
    (happened_before write_introduction event_write_skills_accomplishment)
    (happened_before cover_letter_feedback cover_letter_submission)
    (happened_before event_incorporate_revisions event_polish_cover_letter)
    (happened_before finalize_draft seek_feedback)
    (happened_before cover_letter_draft_completion cover_letter_revision)
    (happened_before seek_feedback event_incorporate_feedback)
    (happened_before storytelling_workshop cover_letter_feedback_request)
    (happened_before event_incorporate_feedback event_final_review)
    (happened_before cover_letter_revision cover_letter_final_review)
    (happened_before greg_feedback_deadline mock_interview_greg)
    (happened_before leslie_networking_event cover_letter_deadline)
    (happened_before cover_letter_final_review cover_letter_submission)
    (happened_after july_22_project_deadline july_18_presentation)
    (happened_before meeting_with_laura team_meeting)
    (happened_before cover_letter_draft_march_25 cover_letter_revision_april_5)
    (happened_before seek_feedback final_edits)
    (happened_before initial_revisions seek_feedback)
    (happened_before documentary_production_2022 event_outline_cover_letter)
    (happened_before write_introduction write_accomplishments)
    (happened_before event_polish_cover_letter event_submit_cover_letter)
    (happened_before event_outline_cover_letter write_introduction)
    (happened_before write_conclusion finalize_draft)
    (happened_before event_draft_mar_25 greg_coaching_session)
    (happened_before event_workshop_mar_20 event_draft_mar_25)
    (happened_before cover_letter_deadline creative_director_meeting)
    (happened_before project_deadline workshop_preparation)
    (happened_before event_write_skills_accomplishment finalize_draft)
    (happened_after progress_report_july_15 caribbean_heritage_lunch)
    (happened_before write_accomplishments write_skills)
    (happened_before seek_feedback event_incorporate_revisions)
    (happened_before cover_letter_submission feedback_deadline_apr14)
    (happened_before greg_coaching_session leslie_networking_event)
    (happened_before seek_feedback event_submit_cover_letter)
    (happened_before write_introduction event_write_second_accomplishment)
  )

  (:goal
    (and (verified_sequence creative_director montserrat_youth_media) (verified_sequence montserrat_youth_media cover_letter))
  )
)
